#!/usr/bin/env bash
#
# Start Anvil and deploy mock contracts for local KAMON development.
#
# Usage:
#   ./scripts/dev-local.sh          # Start Anvil + deploy + generate .env.local
#   ./scripts/dev-local.sh --deploy # Deploy only (Anvil already running)
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS_DIR="$ROOT_DIR/contracts"
ENV_FILE="$ROOT_DIR/.env.local"
ANVIL_PORT=8545
ANVIL_PID=""

cleanup() {
  if [[ -n "$ANVIL_PID" ]]; then
    echo "Stopping Anvil (PID $ANVIL_PID)..."
    kill "$ANVIL_PID" 2>/dev/null || true
  fi
}

deploy() {
  echo "Deploying mock contracts..."
  local output
  output=$(cd "$CONTRACTS_DIR" && forge script script/Deploy.s.sol \
    --rpc-url "http://localhost:$ANVIL_PORT" \
    --broadcast 2>&1)

  echo "$output"

  # Parse deployed addresses from script output
  local seki dojo honoo mizu mori tsuchi kaze resolver bond onchat
  seki=$(echo "$output"   | grep 'VITE_SEKI_TOKEN_ADDRESS='   | sed 's/.*=//')
  dojo=$(echo "$output"   | grep 'VITE_DOJO_TOKEN_ADDRESS='   | sed 's/.*=//')
  honoo=$(echo "$output"  | grep 'VITE_HOUSE_FIRE_ADDRESS='   | sed 's/.*=//')
  mizu=$(echo "$output"   | grep 'VITE_HOUSE_WATER_ADDRESS='  | sed 's/.*=//')
  mori=$(echo "$output"   | grep 'VITE_HOUSE_FOREST_ADDRESS=' | sed 's/.*=//')
  tsuchi=$(echo "$output" | grep 'VITE_HOUSE_EARTH_ADDRESS='  | sed 's/.*=//')
  kaze=$(echo "$output"   | grep 'VITE_HOUSE_WIND_ADDRESS='   | sed 's/.*=//')
  resolver=$(echo "$output" | grep 'VITE_DOJO_RESOLVER_ADDRESS=' | sed 's/.*=//')
  bond=$(echo "$output"   | grep 'VITE_MOCK_BOND_ADDRESS='    | sed 's/.*=//')
  onchat=$(echo "$output" | grep 'VITE_ONCHAT_ADDRESS='       | sed 's/.*=//')

  # Write .env.local
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/dev-local.sh — do not edit manually
# Local Anvil development (chain ID 31337)
VITE_CHAIN_ID=31337

# WalletConnect (not needed for local dev but prevents errors)
VITE_WALLETCONNECT_PROJECT_ID=local-dev-placeholder

# Token addresses
VITE_SEKI_TOKEN_ADDRESS=$seki
VITE_DOJO_TOKEN_ADDRESS=$dojo

# DOJO streak resolution (mock)
VITE_DOJO_RESOLVER_ADDRESS=$resolver
VITE_DOJO_SCHEMA_UID=0x0000000000000000000000000000000000000000000000000000000000000000

# House NFT bonding curves
VITE_HOUSE_FIRE_ADDRESS=$honoo
VITE_HOUSE_WATER_ADDRESS=$mizu
VITE_HOUSE_FOREST_ADDRESS=$mori
VITE_HOUSE_EARTH_ADDRESS=$tsuchi
VITE_HOUSE_WIND_ADDRESS=$kaze

# Mock Bond contract (local only — replaces Mint Club Bond)
VITE_MOCK_BOND_ADDRESS=$bond

# OnChat contract (local mock)
VITE_ONCHAT_ADDRESS=$onchat

# Staking pool (not yet deployed)
VITE_STAKING_POOL_ADDRESS=

# No Alchemy needed for local dev
VITE_ALCHEMY_API_KEY=
EOF

  echo ""
  echo "=== .env.local written ==="
  cat "$ENV_FILE"
}

# --deploy flag: skip Anvil, just deploy
if [[ "${1:-}" == "--deploy" ]]; then
  deploy
  exit 0
fi

# Start Anvil in background
echo "Starting Anvil on port $ANVIL_PORT..."
anvil --port "$ANVIL_PORT" --chain-id 31337 --block-time 1 &
ANVIL_PID=$!
trap cleanup EXIT

# Wait for Anvil to be ready
echo "Waiting for Anvil..."
for i in $(seq 1 30); do
  if curl -s -o /dev/null "http://localhost:$ANVIL_PORT"; then
    echo "Anvil ready."
    break
  fi
  sleep 0.5
done

deploy

echo ""
echo "Anvil running on http://localhost:$ANVIL_PORT (PID $ANVIL_PID)"
echo "Press Ctrl+C to stop."
echo ""

# Keep running
wait "$ANVIL_PID"
